apiVersion: chaos.kreicer.dev/v1alpha1
kind: Experiment
metadata:
  labels:
    app.kubernetes.io/name: omen
    app.kubernetes.io/managed-by: kustomize
  name: experiment-sample
spec:
  # TODO(user): Add fields here
