apiVersion: chaos.kreicer.dev/v1alpha1
kind: Experiment
metadata:
  name: add-latency
  namespace: default
spec:
  runPolicy:
    type: Once
  selector:
    namespace: default
    labels:
      app: my-app
  mode:
    type: random
    count: 1
  action:
    type: network_fault
    networkFault:
      latency: 100ms
      jitter: 10ms
      duration: 5m
