apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "omen.fullname" . }}-manager-role
  labels:
    {{- include "omen.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch]
- apiGroups: [""]
  resources: [pods]
  verbs: [delete, get, list, watch]
- apiGroups: [chaos.kreicer.dev]
  resources: [experiments, experimentruns]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [chaos.kreicer.dev]
  resources: [experiments/finalizers, experimentruns/finalizers]
  verbs: [update]
- apiGroups: [chaos.kreicer.dev]
  resources: [experiments/status, experimentruns/status]
  verbs: [get, patch, update]
