apiVersion: v1
kind: Service
metadata:
  name: {{ include "omen.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omen.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.webhook.port }}
  selector:
    {{- include "omen.selectorLabels" . | nindent 4 }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "omen.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "omen.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "omen.fullname" . }}-serving-cert
  {{- end }}
webhooks:
  - admissionReviewVersions: [v1]
    clientConfig:
      service:
        name: {{ include "omen.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-chaos-kreicer-dev-v1alpha1-experiment
    failurePolicy: Fail
    name: vexperiment.kb.io
    rules:
      - apiGroups: [chaos.kreicer.dev]
        apiVersions: [v1alpha1]
        operations: [CREATE, UPDATE]
        resources: [experiments]
    sideEffects: None
